FROM slskd/slskd:latest

# Install Python and pip
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    python3-requests && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
